#region

#endregion

namespace Client.ChannelInterface;

/// <summary>
///     Identifies a communication communication session. Used when multiple requests/responses are
///     exchanged
///     Empty abstract class. Internal session identifiers are generated by the concrete channels
/// </summary>
public abstract class Session
{
}